/** Frozen UI index matching presets/textanim/index.jsonl. */
export const CAPTION_TEXT_ANIMATIONS = [
    { id: "fade-in-out", label: "Fade", slot: "in" },
    { id: "soft-fade", label: "Soft fade", slot: "in" },
    { id: "fade-up", label: "Fade up", slot: "in" },
    { id: "fade-down", label: "Fade down", slot: "in" },
    { id: "cinematic-fade", label: "Cinematic fade", slot: "in" },
    { id: "slide-left", label: "Slide from left", slot: "in" },
    { id: "slide-right", label: "Slide from right", slot: "in" },
    { id: "slide-up", label: "Slide from bottom", slot: "in" },
    { id: "slide-down", label: "Slide from top", slot: "in" },
    { id: "push-left", label: "Push left", slot: "in" },
    { id: "push-right", label: "Push right", slot: "in" },
    { id: "push-up", label: "Push up", slot: "in" },
    { id: "push-down", label: "Push down", slot: "in" },
    { id: "rise-soft", label: "Soft rise", slot: "in" },
    { id: "drop-in", label: "Drop in", slot: "in" },
    { id: "zoom-in-out", label: "Zoom", slot: "in" },
    { id: "zoom-pop", label: "Zoom pop", slot: "in" },
    { id: "zoom-pulse", label: "Zoom pulse", slot: "in" },
    { id: "pop", label: "Pop", slot: "in" },
    { id: "bounce", label: "Bounce", slot: "in" },
    { id: "squash-pop", label: "Squash", slot: "in" },
    { id: "stretch-in", label: "Stretch", slot: "in" },
    { id: "stomp", label: "Stomp", slot: "in" },
    { id: "snap", label: "Snap", slot: "in" },
    { id: "rotate-in", label: "Rotate in", slot: "in" },
    { id: "spin-in", label: "Spin in", slot: "in" },
    { id: "roll-in", label: "Roll in", slot: "in" },
    { id: "spiral-in", label: "Spiral", slot: "in" },
    { id: "swing", label: "Swing", slot: "in" },
    { id: "shake", label: "Shake", slot: "in" },
    { id: "jitter", label: "Jitter", slot: "in" },
    { id: "glitch", label: "Glitch", slot: "in" },
    { id: "flash", label: "Flash", slot: "in" },
    { id: "heartbeat", label: "Heartbeat", slot: "in" },
    { id: "typewriter", label: "Typewriter", slot: "in" },
    { id: "wipe-left", label: "Wipe left", slot: "in" },
    { id: "wipe-right", label: "Wipe right", slot: "in" },
    { id: "wobble", label: "Wobble", slot: "loop" },
    { id: "float", label: "Float", slot: "loop" },
    { id: "breath", label: "Breathe", slot: "loop" },
    { id: "neon-flicker", label: "Neon flicker", slot: "loop" },
    { id: "hologram", label: "Hologram", slot: "loop" },
    { id: "retro-flicker", label: "Retro flicker", slot: "loop" },
    { id: "caption-rise", label: "Caption rise", slot: "in" },
    { id: "news-ticker", label: "News ticker", slot: "loop" },
    { id: "marquee-left", label: "Scroll horizontal", slot: "loop" },
    { id: "crawl-up", label: "Scroll vertical", slot: "loop" }
] as const;
